FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
WORKDIR /code

COPY . .

RUN dotnet restore

RUN dotnet publish -o /out/ -c Release

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1 AS runtime

COPY --from=build /out /app/

WORKDIR /app

ENTRYPOINT ["dotnet", "CatalogApi.dll"]